name: Wiki Content Sync

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  workflow_dispatch:
  gollum:

env:
  GIT_AUTHOR_NAME: GitHub Action
  GIT_AUTHOR_EMAIL: action@github.com
  SYNC_CHANGES_REPO_NAME: docs-sync

jobs:

  sync-content-to-wiki:
    if: always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && github.event_name != 'gollum'
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: impresscms-dev/strip-markdown-extensions-from-links-action@v1.0.0
        with:
          path: docs
      - name: Sync docs folder to wiki
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}

  job-sync-wiki-to-docs:
    if: github.event_name == 'gollum'
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: wiki
          destination: docs
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: main

      - name: Create pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: wiki
          destination_branch: docs
          pr_title: "[Chore] - Syncing Wiki changes in ${{ env.SYNC_CHANGES_REPO_NAME }} into default branch"
          pr_body: ":crown: *An automated PR* This is an automated PR to sync this repository's wiki docs with your docs in the repo via a PR."
          pr_label: "docs,automation"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}