name: Synchronize the Wiki
on:
  gollum
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lonnen/sync-wiki-to-branch-action@v1.0.0
        with:
          branch: wiki
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}